### ISSUE TITLE
Peer-to-Peer review

### ISSUE THREAD

**Issue by enmanuelbayen** [EmiLoKiJu/Portfolio#17]
The structure of your code is very professional and orderly, congratulations! 

I suggest you change the menu icon to a new `<nav>`  with at ul lis where you show the options in the stigma template. 

I suggest you remove the footer margin from the website.

**Comment by mpa-mxiang** [comment]
For the first section in your page, I would like to kindly suggest:
- Try to get higher priority for background image so that it can shows up for the desktop version
- There are some blanks for your first section, try to use something like `width:100%` to fix it
- The positions for texts and icons are not quite right with the full screen, try to see what's going wrong and fix it:)

**Comment by mpa-mxiang** [comment]
One thing to add, I notice that your class names are like "section1", "section2", etc, this is not clear to know what this section is about, try to have clearer class/id or other possible property names to avoid vague definition.

**Comment by mpa-mxiang** [comment]
Also, I notice there is a scrollbar that moves around for the website, according to one of my previous review, this shows your website actually is not responsive enough 🤖  
Try to add `overflow-x: hidden` or something similar with overflow in your html and/or body css property to see :octocat:
